// engine/ops.js — every change to shared state as a named operation over a plain
// state object. Runs in two places with no other dependency: the browser (where
// state.js's commit() applies an op locally and hands it to whichever window holds
// the session socket) and the Worker's room, which applies the same op to the
// session's document before broadcasting it. If it isn't registered here it isn't
// shared. Ids are generated by the caller and travel in the args, so applying an
// op is deterministic everywhere.
//
// The engine registers the ops every system needs (scene progress, notes, current
// scene, clues, party, maps, the table's map, clocks, the log); a system module registers its own
// (system/<id>/ops.js) with the same call. Roles: 'gm' may send anything;
// 'player' only what a rule permits, against their claimed character.
(function (root, factory) {
  if (typeof module !== 'undefined' && module.exports) module.exports = factory();
  else root.VttOps = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  const OPS = {};
  const PLAYER_RULES = {};
  const PLAYER_FILTERS = [];   // (doc) => doc, applied in order for playerView
  const FOR_PLAYERS = {};      // name -> (doc, args) => {name, args} | null
  const SHARED_KEYS = [];

  const LOCAL = {};            // ops on the GM's own, unshared keys (opts.local): never sent to the room
  const UNCLAIMED = {};        // ops a player may send before claiming a character (opts.unclaimed)

  function register(name, fn, playerRule, forPlayers, opts) {
    OPS[name] = fn;
    if (playerRule) PLAYER_RULES[name] = playerRule;
    if (forPlayers) FOR_PLAYERS[name] = forPlayers;
    if (opts && opts.unclaimed) UNCLAIMED[name] = true;
    if (opts && opts.local) LOCAL[name] = true;
  }

  function shared(keys) {
    keys.forEach((k) => {
      if (SHARED_KEYS.indexOf(k) === -1) SHARED_KEYS.push(k);
    });
  }

  function playerFilter(fn) {
    PLAYER_FILTERS.push(fn);
  }

  function apply(s, name, args) {
    const fn = OPS[name];
    if (!fn) throw new Error('Unknown op ' + name);
    fn.apply(null, [s].concat(args || []));
  }

  function permits(s, role, memberId, name, args) {
    if (!OPS[name]) return false;
    if (role === 'gm') return true;
    if (role !== 'player') return false;
    if (!memberId && !UNCLAIMED[name]) return false;
    const rule = PLAYER_RULES[name];
    return !!rule && !!rule(s, memberId, args || []);
  }

  function playerView(s) {
    let doc = {};
    SHARED_KEYS.forEach((k) => {
      if (s[k] !== undefined) doc[k] = JSON.parse(JSON.stringify(s[k]));
    });
    PLAYER_FILTERS.forEach((f) => {
      doc = f(doc) || doc;
    });
    return doc;
  }

  function forPlayers(s, name, args) {
    const f = FOR_PLAYERS[name];
    return f ? f(s, args) : { name, args };
  }

  function sharedSlice(s) {
    const out = {};
    SHARED_KEYS.forEach((k) => {
      if (s[k] !== undefined) out[k] = s[k];
    });
    return out;
  }

  // ── the engine's own ops ─────────────────────────────────────────
  shared(['current', 'progress', 'clues', 'party', 'maps', 'table', 'clocks', 'log', 'campaign', 'order']);

  function bag(s, key) {
    if (!s[key]) s[key] = {};
    return s[key];
  }

  register('setCampaign', (s, patch) => {
    s.campaign = Object.assign({}, s.campaign || {}, patch);
  });
  register('setCurrentScene', (s, moduleId, sceneId) => {
    bag(s, 'current')[moduleId] = sceneId;
  });
  // the GM's arrangement of a module: scenes grouped into phases, in their order; the cast in
  // its order. Ids not listed keep the book's place (system/<id>/table.js resolves).
  //   order.scenes[moduleId] = [{ name: phaseName, scenes: [sceneId…] }…]
  //   order.cast[moduleId]   = [entityId…]
  register('setSceneOrder', (s, moduleId, phases) => {
    bag(bag(s, 'order'), 'scenes')[moduleId] = phases;
  });
  register('setCastOrder', (s, moduleId, ids) => {
    bag(bag(s, 'order'), 'cast')[moduleId] = ids;
  });
  register('setSceneDone', (s, moduleId, sceneId, done) => {
    const m = bag(bag(s, 'progress'), moduleId);
    m[sceneId] = Object.assign({}, m[sceneId] || {}, { done: !!done });
  });
  register('setSceneNotes', (s, moduleId, sceneId, notes) => {
    const m = bag(bag(s, 'progress'), moduleId);
    m[sceneId] = Object.assign({}, m[sceneId] || {}, { notes: notes || '' });
  }, null, () => null);   // GM notes never go to players
  register('setClueRevealed', (s, moduleId, sceneId, clueName, revealed) => {
    const m = bag(bag(s, 'clues'), moduleId);
    m[sceneId + '::' + clueName] = !!revealed;   // the key the Scene panel reads (clueKey)
  });
  register('appendLog', (s, entry) => {
    if (!s.log) s.log = [];
    s.log.push(entry);
    if (s.log.length > 500) s.log.splice(0, s.log.length - 500);
  }, (s, me, a) => !!a[0] && a[0].memberId === me);
  // clocks: { id, name, segments, filled, sceneId|null, visible }
  register('setClock', (s, clock) => {
    if (!s.clocks) s.clocks = [];
    const i = s.clocks.findIndex((c) => c.id === clock.id);
    if (i === -1) s.clocks.push(clock);
    else s.clocks[i] = Object.assign({}, s.clocks[i], clock);
  }, null, (s, a) => (a[0] && a[0].visible === false ? null : { name: 'setClock', args: a }));
  register('removeClock', (s, id) => {
    s.clocks = (s.clocks || []).filter((c) => c.id !== id);
  });
  // party members: { id, templateId, name, live: {…system-defined…}, notes }
  // a player may bring their own character: one made on the site, loaded from its file
  // (source.kind 'file'), before or after claiming; anything else is the GM's to add
  register('addPartyMember', (s, m) => {
    if (!s.party) s.party = [];
    if (!s.party.some((x) => x.id === m.id)) s.party.push(m);
  }, (s, me, a) => !!a[0] && !!a[0].id && !!a[0].templateId && !!a[0].source && a[0].source.kind === 'file',
  (s, a) => ({ name: 'addPartyMember', args: [Object.assign({}, a[0], { notes: '' })] }), { unclaimed: true });
  register('removePartyMember', (s, id) => {
    s.party = (s.party || []).filter((m) => m.id !== id);
  });
  register('setPartyLive', (s, id, patch) => {
    const m = (s.party || []).find((x) => x.id === id);
    if (m) m.live = Object.assign({}, m.live || {}, patch);
  }, (s, me, a) => a[0] === me);
  register('setPartyNotes', (s, id, notes) => {
    const m = (s.party || []).find((x) => x.id === id);
    if (m) m.notes = notes;
  }, null, () => null);
  register('setPartyPlayerNotes', (s, id, notes) => {
    const m = (s.party || []).find((x) => x.id === id);
    if (m) m.playerNotes = notes;
  }, (s, me, a) => a[0] === me);
  // maps: per map id { image, w, h, grid:{size,ox,oy}, fog:[…], tokens:[…], effects:[…] }.
  // A map id is one the system ships (a floor of a building, the grounds) or, for a
  // scene with no shipped map, the scene id itself. The table shows one map at a
  // time; which one is shared state (table.map), so the player view follows it.
  register('setMapState', (s, mapId, map) => {
    bag(s, 'maps')[mapId] = map;
  }, null, (s, a) => ({ name: 'setMapState', args: [a[0], filterMap(a[1])] }));
  register('setTableMap', (s, mapId) => {
    s.table = Object.assign({}, s.table || {}, { map: mapId });
  });
  register('setTokenPosition', (s, mapId, tokenId, x, y) => {
    const map = (s.maps || {})[mapId];
    const t = map && (map.tokens || []).find((tk) => tk.id === tokenId);
    if (t) {
      t.x = x;
      t.y = y;
    }
  }, (s, me, a) => {
    const map = (s.maps || {})[a[0]];
    const t = map && (map.tokens || []).find((tk) => tk.id === a[1]);
    return !!t && t.owner === me;
  }, (s, a) => {
    const map = (s.maps || {})[a[0]];
    const t = map && (map.tokens || []).find((tk) => tk.id === a[1]);
    return t && t.hidden ? null : { name: 'setTokenPosition', args: a };
  });

  function filterMap(map) {
    if (!map) return map;
    return Object.assign({}, map, { tokens: (map.tokens || []).filter((t) => !t.hidden) });
  }

  playerFilter((doc) => {
    if (doc.progress) {
      Object.keys(doc.progress).forEach((mod) => {
        Object.keys(doc.progress[mod]).forEach((sc) => {
          doc.progress[mod][sc] = { done: !!doc.progress[mod][sc].done };
        });
      });
    }
    if (doc.party) doc.party = doc.party.map((m) => Object.assign({}, m, { notes: '' }));
    if (doc.maps) Object.keys(doc.maps).forEach((k) => (doc.maps[k] = filterMap(doc.maps[k])));
    if (doc.clocks) doc.clocks = doc.clocks.filter((c) => c.visible !== false);
    return doc;
  });

  return { OPS, PLAYER_RULES, SHARED_KEYS, LOCAL, register, shared, playerFilter, apply, permits, playerView, forPlayers, sharedSlice };
});
